version: '2.2'
services:
  etcd:
    image: marksugar/coreos-etcd:v3.3.10
    container_name: etcd
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /data/etcd:/data/etcd
      - /etc/kubernetes/pki/etcd/:/etc/kubernetes/pki/etcd/
    command: "etcd -name ${PEER_NAME} --data-dir /data/etcd -advertise-client-urls https://${PRIVATE_IP}:2379,https://${PRIVATE_IP}:4001 -listen-client-urls https://0.0.0.0:2379,https://0.0.0.0:4001 -initial-advertise-peer-urls https://${PRIVATE_IP}:2380 -listen-peer-urls https://0.0.0.0:2380 --cert-file=/etc/kubernetes/pki/etcd/server.pem --key-file=/etc/kubernetes/pki/etcd/server-key.pem --client-cert-auth --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem --peer-cert-file=/etc/kubernetes/pki/etcd/peer.pem --peer-key-file=/etc/kubernetes/pki/etcd/peer-key.pem --peer-client-cert-auth --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.pem -initial-cluster-token etcd-cluster -initial-cluster etcd1=https://${etcd0_ip_address}:2380,etcd2=https://${etcd1_ip_address}:2380,etcd3=https://${etcd2_ip_address}:2380 -initial-cluster-state new "
    cpu_shares: 90
    mem_limit: 2048m
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
    labels:
      SERVICE_TAGS: etcd
